### ISSUE TITLE
Talent as a switch condition?

### ISSUE THREAD

**Issue by david-driscoll** [corporategoth/rotationmaster#1]
Would it be possible to get talent as a switch condition?  This would make it great on wotlk beta!

Making different rotations for retribution and protection that switch when I switch talents would be great!

![image](https://user-images.githubusercontent.com/1269157/180504352-68aa5d7a-d682-45d2-808a-41e7cc6efc41.png)

![image](https://user-images.githubusercontent.com/1269157/180504408-761198f8-4df2-41ac-aa9b-3e5d2052f1c6.png)

**Comment by corporategoth** [comment]
With Wrath, some of the code that is currently available in Retail will be unlocked again (though it will have to be modified.

Specifically, in Retail, you have multiple talents - so you actually get a tab for each talent, and a separate set of rotations for each spec.

You won't need to have switch conditions for talents.

**Comment by corporategoth** [comment]
Should be resolved as of 1.4.0 beta1
