### ISSUE TITLE
Error only when these addons are used:  Arkinventory, Pawn, Reagent Recipe Classic, Rotation Master

### ISSUE THREAD

**Issue by rbpaiett** [corporategoth/rotationmaster#10]
I'm not sure what to think of this, only when these addons are enabled (Arkinventory, Pawn, Reagent Recipe Classic, & Rotation Master)  and using the Arkinventory search shortcut does this error appear.  If any one of these 4 are disabled, the error doesn't show up.  It reappears after relogging or after reload.

Strange that is only points toward the Rotation Master addon.

The problem DOES go away when Rotation Master 1.3.9 is used instead.

79x RotationMaster\main.lua:1622: attempt to call method 'UpdateSpell' (a nil value)
[string "@RotationMaster\main.lua"]:1622: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

The versions are:

Arkinventory (3.09.67)
Pawn (2.5.38)
Reagent Recipe Classic (2.0.3)
Rotation Master (1.4.1)

**Comment by corporategoth** [comment]
Thanks for the report - this should be fixed with 1.4.1a (which is updated for just this fix)

**Comment by rbpaiett** [comment]
Works just fine, thanks!
