### ISSUE TITLE
Unable to Import Rotation

### ISSUE THREAD

**Issue by rhodan412** [corporategoth/rotationmaster#11]
When attempting to import using v1.4.1a I receive the following error (the below issue/error goes away and I can import if I use v1.4.0):

1x RotationMaster\Options/general.lua:522: attempt to call method 'UpgradeRotationItemsToItemSets' (a nil value)
[string "@RotationMaster\Options/general.lua"]:522: in function <RotationMaster\Options/general.lua:519>
[string "=[C]"]: ?
[string "@Questie\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Questie\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Questie\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Questie\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...stie\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by corporategoth** [comment]
Thanks for the report - I see the problem, this call can likely be eliminated now.  I'll update it for the next version, but I will likely not make a new release for just this issue.

**Comment by corporategoth** [comment]
If you want to fix this locally, remove line 522 of general.lua (that looks like `addon:UpgradeRotationItemsToItemSets(rot)` ).
