### ISSUE TITLE
ENHANCEMENT REQ: Rotation Profiles

### ISSUE THREAD

**Issue by rhodan412** [corporategoth/rotationmaster#12]
Could you implement the ability to save the rotation to a profile?  I play multiple toons of the same class (Classic Realms) and rather than importing to each of these toons whenever a change is made, it would be awesome if your addon could just update the Rotation for that profile (ie Warrior).

**Comment by corporategoth** [comment]
This has been added in 1.4.2 beta 1

**Comment by rhodan412** [comment]
Thank you
