### ISSUE TITLE
Lua error Shaman Totems

### ISSUE THREAD

**Issue by Padparadscha** [corporategoth/rotationmaster#15]
Message: ...\AddOns\RotationMaster\LibsAugment\Totem-EditBox.lua:23: attempt to call global 'GetSpecialization' (a nil value)
Time: Fri Sep  9 13:59:32 2022
Count: 1
Stack: ...\AddOns\RotationMaster\LibsAugment\Totem-EditBox.lua:23: attempt to call global 'GetSpecialization' (a nil value)
[string "@Interface\AddOns\RotationMaster\LibsAugment\Totem-EditBox.lua"]:23: in function <...\AddOns\RotationMaster\LibsAugment\Totem-EditBox.lua:13>
[string "@Interface\AddOns\RotationMaster\LibsAugment\Totem-EditBox.lua"]:59: in function `?'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\RotationMaster\Conditions/common.lua"]:50: in function `Widget_SpellWidget'
[string "@Interface\AddOns\RotationMaster\Conditions/totem.lua"]:81: in function `widget'
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:790: in function `widget'
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:591: in function <...erface\AddOns\RotationMaster\Options/conditional.lua:443>
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:584: in function <...erface\AddOns\RotationMaster\Options/conditional.lua:443>
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:620: in function `LayoutConditionFrame'
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:376: in function <...erface\AddOns\RotationMaster\Options/conditional.lua:374>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Window.lua"]:31: in function <...rnals\Ace3\AceGUI\widgets\AceGUIContainer-Window.lua:30>
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceGUI\widgets\AceGUIContainer-Window.lua"]:87: in function `Hide'
[string "@Interface\AddOns\RotationMaster\Options/conditional.lua"]:226: in function <...erface\AddOns\RotationMaster\Options/conditional.lua:224>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-InteractiveLabel.lua"]:23: in function <...AceGUI-3.0\widgets\AceGUIWidget-InteractiveLabel.lua:22>

Locals: <none>

**Comment by corporategoth** [comment]
It would help to know:
1. What version of Rotation Master you are using.
2. What version of WoW you are playing
3. The condition you are trying to use

**Comment by corporategoth** [comment]
Actually, I reproduced it.  This will be fixed in 1.4.2 when it's released (or in 1.4.2 beta 2 if if there is one).
