### ISSUE TITLE
Missing bleed effects from debuff types

### ISSUE THREAD

**Issue by SchneiderA** [corporategoth/rotationmaster#16]
As a rogue, I wish to have conditions for Hunger For Blood so that it only shows if a bleed debuff is present on my target.

**Comment by corporategoth** [comment]
Unfortunately, WoW doesn't give an API to show if a target is effected by a bleed effect.
[UnitDebuff](https://wowpedia.fandom.com/wiki/API_UnitAura) can detect Magic, Disease, Poison and Curses.  But not bleeds, stuns, slow, root. fears, etc.  The only way to do something like that is compile a custom list of spells and effects, and keep that in the addon and check if those specific debuffs are present.  Something I've not wanted to do/maintain thus far.

**Comment by SchneiderA** [comment]
That sucks.
I don't think there will be much maintenance after first version on such a list, but I have never developed an addon so I wouldn't know.
Thank you for your comment and love the addon.
