### ISSUE TITLE
WotLK: Glyph

### ISSUE THREAD

**Issue by captnrexx** [corporategoth/rotationmaster#22]
The glyph condition didnt work correct

Without the glyph check, the cooldown conditions work. The glyph  is insert.

![image](https://user-images.githubusercontent.com/1652448/192361164-a694ba69-85d7-45e1-a230-397616018e10.png)

**Comment by corporategoth** [comment]
Will be fixed in the next version.

**Comment by corporategoth** [comment]
Fixed in 1.4.3
