### ISSUE TITLE
WOTLK: 1.4.3.beta 4

### ISSUE THREAD

**Issue by captnrexx** [corporategoth/rotationmaster#25]
10x RotationMaster\main.lua:1689: attempt to index field 'damageHistory' (a nil value)
[string "@RotationMaster\main.lua"]:1689: in function <RotationMaster\main.lua:1648>
[string "@RotationMaster\main.lua"]:1701: in function <RotationMaster\main.lua:1701>
[string "@RotationMaster\main.lua"]:1268: in function `?'
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by captnrexx** [comment]
1x RotationMaster\main.lua:635: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@RotationMaster\main.lua"]:635: in function `SwitchRotation'
[string "@RotationMaster\main.lua"]:1286: in function `func'
[string "@BulkMail2\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <BulkMail2\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by captnrexx** [comment]
3x RotationMaster\main.lua:1147: attempt to index field 'specSpells' (a nil value)
[string "@RotationMaster\main.lua"]:1147: in function `UpdateSpecSpells'
[string "@RotationMaster\main.lua"]:1180: in function `UpdateSkill'
[string "@RotationMaster\main.lua"]:503: in function `enable'
[string "@RotationMaster\main.lua"]:529: in function <RotationMaster\main.lua:521>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by captnrexx** [comment]
1x RotationMaster\init.lua:476: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@RotationMaster\init.lua"]:476: in function <RotationMaster\init.lua:474>
[string "@RotationMaster\init.lua"]:566: in function `init'
[string "@RotationMaster\main.lua"]:278: in function <RotationMaster\main.lua:266>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by corporategoth** [comment]
Are you still seeing an issue with 1.4.3 (release)?

**Comment by rbpaiett** [comment]
Wow, this last update really caused a lot of errors, especially the damage history:

98x RotationMaster\main.lua:1689: attempt to index field 'damageHistory' (a nil value)
[string "@RotationMaster\main.lua"]:1689: in function <RotationMaster\main.lua:1648>
[string "@RotationMaster\main.lua"]:1701: in function <RotationMaster\main.lua:1701>
[string "@RotationMaster\main.lua"]:1268: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by corporategoth** [comment]
I believe these are secondary errors.  Can you try removing line 566 from init.lua?

It just has the following:
```
upgradeBindingSlots()
```

It's already been reported that was an issue, and likely the rest of this is all secondary to that issue.
I'll release an update if this fixes it.

**Comment by corporategoth** [comment]
Fixed with 1.4.3d

**Comment by rbpaiett** [comment]
This error doesn't appear any more but another has popped up.  I made a new entry in issues.
