### ISSUE TITLE
Arcane Blast charges not detectable

### ISSUE THREAD

**Issue by Schusti77** [corporategoth/rotationmaster#3]
Hello,
I can't detect the spell charges of Arcane Blast with that addon. I tried to highlight trinkets when 3 Stacks of Arcane Blast are there but it dosn't get triggered. I tried to detect this as
- Buff
- Debuff
- Spell charge (think this is the right one)
- Spell Time Remaining
The Condition never gets satisfied. I'm using the german client, but other spells are working so this seams to be no problem.

kind regards

**Comment by corporategoth** [comment]
For some reason, this counts as a deubff on yourself.

So you need to make a condition for Debuff Stacks, with the unit of 'you', and the spell 'Arcane Blast'.

I just tested this.  I guess it's a debuff because it increases the mana cost, despite also increasing damage.
