### ISSUE TITLE
[Enhancement] Insecure display frame

### ISSUE THREAD

**Issue by Anonomit** [corporategoth/rotationmaster#5]
Instead of causing an effect on the actionbars, I would like to have a frame visible which shows the icon of the next spell to cast. I would be able to resize and move this frame, but it would of course not be clickable. I wouldn't want it to have any effect.

Not all of my actionbar spells are visible at all times, as some only cast when a modifer key is held down. Unless I change many of my keybinds, actionbar effects will not work for me. This is why I would prefer to have a single spot on my screen that I can view for a recommendation of what spell to cast next.

**Comment by corporategoth** [comment]
I added this to 1.4.2 beta 1
