### ISSUE TITLE
Error at logon after 140 update

### ISSUE THREAD

**Issue by rbpaiett** [corporategoth/rotationmaster#8]
This happened right when I logged on:

2x ...Master\Libs\AceGUI-3.0-41-Spell-EditBox\SpellLoader.lua:217: attempt to index field '?' (a nil value)
[string "@RotationMaster\Libs\AceGUI-3.0-41-Spell-EditBox\SpellLoader.lua"]:217: in function `UpdateFromSpellBook'
[string "@RotationMaster\main.lua"]:1079: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by corporategoth** [comment]
I found the issue, it will be fixed next version.

https://github.com/corporategoth/rotationmaster/commit/546d1c6c78484d246cc8647474fd66f80e62275d

**Comment by rbpaiett** [comment]
I manually added your fix and ended up with a 2nd error along with the original:

10x ...Master\Libs\AceGUI-3.0-41-Spell-EditBox\SpellLoader.lua:76: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@RotationMaster\Libs\AceGUI-3.0-41-Spell-EditBox\SpellLoader.lua"]:76: in function <...Master\Libs\AceGUI-3.0-Spell-EditBox\SpellLoader.lua:71>
[string "@RotationMaster\Libs\AceGUI-3.0-41-Spell-EditBox\SpellLoader.lua"]:216: in function `UpdateFromSpellBook'
[string "@RotationMaster\main.lua"]:1079: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by corporategoth** [comment]
What class are you playing?
On what edition of WoW?

**Comment by rbpaiett** [comment]
I am playing a hunter-beast master and it's the latest classic TBC edition.

**Comment by rbpaiett** [comment]
Just to be sure, this only happens with my hunter, all others it works just fine.  I even tried repeating it with just the one addon and it only errored out with the hunter.

**Comment by corporategoth** [comment]
This should be fixed, test it with the 1.4.1 Beta

**Comment by rbpaiett** [comment]
Ok will do.

**Comment by rbpaiett** [comment]
It works just fine, excellent!
