### ISSUE TITLE
Unable to Load Addon

### ISSUE THREAD

**Issue by Mirchako** [corporategoth/rotationmaster#9]
Made rotation for Amrs Warrior on Prepatch PTR

Worked fine untill i aquired dual spec and made some macros. 
Now i cannot open settings. I get the following LUA error when I try:

Message: Interface\AddOns\RotationMaster\main.lua:403: attempt to index field 'optionsFrames' (a nil value)
Time: Sun Aug 14 16:48:13 2022
Count: 4
Stack: Interface\AddOns\RotationMaster\main.lua:403: attempt to index field 'optionsFrames' (a nil value)
[string "@Interface\AddOns\RotationMaster\main.lua"]:403: in function `OnClick'
[string "@Interface\AddOns\AtlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...tlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals: _ = LibDBIcon10_RotationMaster {
 0 = <userdata>
 fadeOut = <unnamed> {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 showOnMouseover = true
 Show = <function> defined =[C]:-1
 SetParent = <function> defined =[C]:-1
 db = <table> {
 }
 icon = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
}
button = "LeftButton"
frame = RotationMasterLDBFrame {
 0 = <userdata>
}
dropdownFrame = RotationMasterLDBDropdownFrame {
 0 = <userdata>
 Text = RotationMasterLDBDropdownFrameText {
 }
 Icon = RotationMasterLDBDropdownFrameIcon {
 }
 Button = RotationMasterLDBDropdownFrameButton {
 }
 Right = RotationMasterLDBDropdownFrameRight {
 }
 Middle = RotationMasterLDBDropdownFrameMiddle {
 }
 Left = RotationMasterLDBDropdownFrameLeft {
 }
}
(*temporary) = <function> defined @Interface\FrameXML\InterfaceOptionsFrame.lua:423
(*temporary) = nil
(*temporary) = RotationMasterLDBFrame {
 0 = <userdata>
}
(*temporary) = "UIDropDownMenuTemplate"
(*temporary) = RotationMasterLDBDropdownFrame {
 0 = <userdata>
 Text = RotationMasterLDBDropdownFrameText {
 }
 Icon = RotationMasterLDBDropdownFrameIcon {
 }
 Button = RotationMasterLDBDropdownFrameButton {
 }
 Right = RotationMasterLDBDropdownFrameRight {
 }
 Middle = RotationMasterLDBDropdownFrameMiddle {
 }
 Left = RotationMasterLDBDropdownFrameLeft {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 788
 BT4Button46Shine5 = BT4Button46Shine5 {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 406
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 LFGBrowseGroupDataDisplayRoleCount_Update = <function> defined @Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:699
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFr.

The rotation itself still works if i do /rm toggle. just cant oppen settins to change anything, also cant use it on second talent spec

**Comment by corporategoth** [comment]
Can you test if this is still an issue in 1.4.1 Beta?

**Comment by Mirchako** [comment]
Hello,

Issue was still present so i had to reset the addon. 
It seems there was something in the rotation that caused it to bug at some point (even though initially it worked fine). I was unable to open it ingame to modify.
This is the rotation i was using, if it helps:

AzReBAAuSdA2Es2URM0mdVMS+UZoJ6i9aLfEfgh+SkrDFPxWaiiEajCghosclCTHB
M4ptFBSLQVgsaDlED2UBJ6qloE8VzRREpoq1WRR0ykXAXQVSl2muk6wkYTNUGyHkt
NCj6H6LEl9h1BGQshhotGSYhxJfwG5BXRNSuchPZNimpLbAM2AnUdukxZ3YSccsPP
CdKAiAZ0hb2hyfibXmpe4xV0IQ8NS+Zh5OYp5QZgRHPIawTVCLagG3oJNKEd8EFXp
vnh8lxwt7jLZeSypBWcnHLDzWFILzs4bmpyvYysU/EyuNV+XZtoRgF+zBeOFEo1PW
qKOpPGGJufh2k4jDLHzhibn69gKBT+Ta83Xtc8ZSzUC8MYgAFeK1TXGCyUan7REHU
kj3LDTaLyhyflaADQ+xylD7ZkhjTDEzgvTgYoEdIa8ocn5mVxrXuIWdyEMtdCg8jH
zS8ytqGIasFHXCK42LzCUDQb0EBqGQVzKRs08vkuOFneZ7DyW1IKz84Ym5ysCrGMr
FPxMrjUPwEvmhRKNN4msdqPxhibn4dpOoxFu2HlhOlCRgM6QNzQ5P5NrzUvc4i6Ex
UZdfMx8g8lhzqMI5gASwdUMIjiGMgCXOLqHqqqKOIbHd8nR4i6TnTc0OV/HVij4mV
xrvstpjgCM2UgE4LreO/NCicYnLVFH0miEFzsvTAcqEtAZ8oYm52dyrXmJW9yFMNR
CjZKPmRdzIELKjIPqoGzBhWMGcFSuAMSXDFwGOWwgkcd3ydHiLpOdx5JacHbCATtv
aHK+jq1Q8DO51vyFnL0gAFd0aTW8UKLxSUvUkTTCEDuPJbXghIcKId7Q5DwigFWVO
yLEK+j8To6UtpF8ZYB/R1QF80KJxptEVrvRCDfsNBpvaHK+FgCNRrhl54XpQEUCOk
Pe0OT8TK41L3GLuxCGWmhBfMx8C6lSLjUAVTVowYXjGQwHXyAmjy1mqVAoqjiNsJK
dF6YDFQnoDHlDk/Mzuda8xC3uQrgZGmjxMfMD1GSMUgzAHKwRXIEIgWOrFEFX4gsK
AtFVseXxXXK0uMtk54USjU9aoo7kDU3OV6qCq2g0Gj8Ri4bXsNNoJA==

If i import it, i get the same error as previously. 
I noticed that some conflicts in the rotations tend to bug out the whole addon (on all chars) instead of just the one rotation. 
I had a similar issue when i selected a mana condition for the warrior, when i started using the addon. Had to reset it to make it work again.
/rm toggle still worked so maybe you should consider a full reset command until this sort of issue happens less often.

Also, v 1.41 beta seems to be missing proc based buffs like "Taste for blood" or "Sudden Death" on the buff present conditton.

**Comment by corporategoth** [comment]
re: buffs - I don't list buffs or debuffs.  I just use what Blizzard sets.
When you say missing, do you mean you can't choose it? or conditions with it aren't firing.  If the latter, check they aren't actually debuffs (there was a mage proc buff that Blizzard actually identified as a debuff).
